[build]
target = "crates/web/index.html"
dist = "crates/web/dist"

[[proxy]]
rewrite = "/api"
backend = "http://127.0.0.1:44714/api"

[[proxy]]
rewrite = "/ws"
backend = "ws://127.0.0.1:44714/ws"
ws = true
