#!/bin/sh

set -e

trunk build --release
cargo build --release --features gnome,bundle -p jpv
rm -f target/generate-rpm/jpv-*.rpm
cargo generate-rpm -p crates/jpv
sudo dnf reinstall --assumeyes target/generate-rpm/jpv-*.rpm
